### ISSUE TITLE
Font name issues when multiple are installed

### ISSUE THREAD

**Issue by robmcmullen** [TheRobotFactory/EightBit-Atari-Fonts#1]
I installed a few fonts to see how they worked. They're great, and I love the variety that you've found. (I'll probably import them all into Omnivore at some point, thank-you-in-advance!)

On linux, each application seems to show the fonts differently. There are 3 fonts installed:
```
$ ls -l ~/.fonts/EightBit\ Atari-*
-rw-r--r-- 1 rob users 123240 Mar 11 09:30 '/home/rob/.fonts/EightBit Atari-Balloon.ttf'
-rw-r--r-- 1 rob users 124972 Mar 11 09:34 '/home/rob/.fonts/EightBit Atari-Homepack.ttf'
-rw-r--r-- 1 rob users 113060 Mar 11 09:28 '/home/rob/.fonts/EightBit Atari-Regular.ttf'
```

Gimp shows there are 3 different fonts, but they all share the name "Eightbit Atari" and I can't tell if the font sample is different or from the same font:
![gimp-font-list](https://user-images.githubusercontent.com/896656/54142838-c862ca00-43e5-11e9-9924-1f659d875977.png)
Libre office shows one font and it seems to use the glyphs from Regular
![libre-office-font-menu](https://user-images.githubusercontent.com/896656/54142865-d87aa980-43e5-11e9-9ff4-cd0357f421d2.png)
And the wxPython font dialog shows the 3 font names, but uses the glyphs from Balloon and also somehow finds some bold/italic versions as well.
![wxpython-font-dialog](https://user-images.githubusercontent.com/896656/54143094-58a10f00-43e6-11e9-9489-575012fa7665.png)

**Comment by a8bit** [comment]
Hi Rob! Thanks for the kind words :) 

I always get annoyed when people say this to me so I'm sorry for saying this to you but...

The Apps are all doing it wrong. 

I'm using the weight of the font to identify the different faces, just like you find with other fonts that put 'not strictly weight' into the weights like "outline" or "3d handtooled" variants of a face. 

That should give you a list of fonts with a single font in it called "EightBit Atari" and where you would drop down for the different weights you should see Balloon, Homepack and Regular

Gimp is collapsing that hierarchy to present a flat list, you can see the different weights in fira sans there) it isn't bothering to display the weight name. I don't know why, maybe it's some difference in the way it handles ttf and otf fonts?

Libre Office appears to be doing the font display right. Do you have  **B** *I* __U__ icons there with a little dropdown for other weights? you might find them there. If not, it looks like that's missing functionality. Notice you don't get the different Fira sans weights there either, just the faces Fira Sans, Fira Sans Book, and Fira Sans Eight

![Screenshot 2019-03-12 at 14 54 45](https://user-images.githubusercontent.com/12753/54231667-ec520880-44d6-11e9-963a-38c8296aa812.jpg)

wxPython is doing it right, but its being lazy and not using the weight to display the weight name (looks like it's hitting the first one alphabetically, so getting balloon on yours and just using that font for all the weights) the bold/italic/bold italic are being generated programatically the way Windows/Macs did it in the days of Windows 95 and System 7 by slanting the font for italic and stretching it for bold when it can't find a matching face name. 

When the software does it right you get this... 

![Screenshot 2019-03-12 at 14 31 55](https://user-images.githubusercontent.com/12753/54231963-9df13980-44d7-11e9-88e7-160cb7a9a9ac.jpg)
![Screenshot 2019-03-12 at 14 32 40](https://user-images.githubusercontent.com/12753/54231979-a8133800-44d7-11e9-977e-b79afa0595fa.jpg)
![Screenshot 2019-03-12 at 14 34 13](https://user-images.githubusercontent.com/12753/54231998-b2353680-44d7-11e9-8cde-92b445342e2e.jpg)

I'd report this as a bug to the maintainers of the apps you are using.

**Comment by robmcmullen** [comment]
Haha, I read that as one big long "sigh!". Sorry about that. :smile: Thank you for taking the time to write out the detailed response.

Maybe linux is just not working the same way as MacOS. I just upgraded to Libre Office 6.1 and I don't have the same UI with the little arrow in the toolbar, although it does have it in a sidebar. In my case, it doesn't indicate an extra typeface, but the line style for the underline:
![libre-office-litttle-arrow](https://user-images.githubusercontent.com/896656/54247494-6d6cc800-44f6-11e9-9104-068773c788b1.png)
Linux seems to store each typeface/weight/whatever as a different file, although I see where it doesn't show the Italic weight in the list. Maybe dumb applications are just looking for bold/italic and barfing on other weight strings. Lazy.
```
/usr/share/fonts/fira-sans
/usr/share/fonts/fira-sans/FiraSans-Bold.otf
/usr/share/fonts/fira-sans/FiraSans-BoldItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Book.otf
/usr/share/fonts/fira-sans/FiraSans-BookItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Eight.otf
/usr/share/fonts/fira-sans/FiraSans-EightItalic.otf
/usr/share/fonts/fira-sans/FiraSans-ExtraBold.otf
/usr/share/fonts/fira-sans/FiraSans-ExtraBoldItalic.otf
/usr/share/fonts/fira-sans/FiraSans-ExtraLight.otf
/usr/share/fonts/fira-sans/FiraSans-ExtraLightItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Four.otf
/usr/share/fonts/fira-sans/FiraSans-FourItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Hair.otf
/usr/share/fonts/fira-sans/FiraSans-HairItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Heavy.otf
/usr/share/fonts/fira-sans/FiraSans-HeavyItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Italic.otf
/usr/share/fonts/fira-sans/FiraSans-Light.otf
/usr/share/fonts/fira-sans/FiraSans-LightItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Medium.otf
/usr/share/fonts/fira-sans/FiraSans-MediumItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Regular.otf
/usr/share/fonts/fira-sans/FiraSans-SemiBold.otf
/usr/share/fonts/fira-sans/FiraSans-SemiBoldItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Thin.otf
/usr/share/fonts/fira-sans/FiraSans-ThinItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Two.otf
/usr/share/fonts/fira-sans/FiraSans-TwoItalic.otf
/usr/share/fonts/fira-sans/FiraSans-Ultra.otf
/usr/share/fonts/fira-sans/FiraSans-UltraItalic.otf
/usr/share/fonts/fira-sans/FiraSans-UltraLight.otf
/usr/share/fonts/fira-sans/FiraSans-UltraLightItalic.otf
/usr/share/fonts/fira-sans/encodings.dir
/usr/share/fonts/fira-sans/fonts.dir
/usr/share/fonts/fira-sans/fonts.scale
```
Anyway, maybe I'm just out of luck. I really don't expect to use more than just the regular Atari font very often anyway, so I can just reinstall a font as a one-off.

**Comment by a8bit** [comment]
The way the fonts are organised in linux is much the same as macOS and Windows, those folders aren't really required but it does make things neater. I'll have a look at a few of the default fonts and see how they are naming things to see if I've flubbed somewhere.

I put a few of the Atari fonts in ~/.fonts as a test and libre office only shows one of them, my dropdown is the same as yours so blah!

There is one workaround if you only want a few of the fonts installed, that is to edit the family name in FontForge. It's pretty simple (but obviously a nightmare if you want all 350 fonts). Here's the dialog you need to edit...
![Screenshot 2019-03-13 at 10 04 14](https://user-images.githubusercontent.com/12753/54290152-730af200-4578-11e9-8b20-de002f85c1c4.jpg)
It's the first item in the element menu.

Getting you that screenshot did uncover an error in the font metrics, so thanks for that, it seems Postscript doesn't like spaces in font names (otf and ttf are fine with it so it's not causing a problem with the fonts, but fontforge complains) so I'm going to have to fix that. Sadly at the moment my install of fontforge is broken, my package manager "Homebrew" decided to do away with custom options and then let everyone update to newer versions without any of the custom options they had previously set :/ Now I just get told by python that it cant find homebrew. Bigger issues loom as some of the software im using requires python2 and hasn't been updated for 3 yet.

**Comment by Vaults** [comment]
As @TheRobotFactory mentioned, there is a workaround for setting the family, I'm writing this extra comment to show how to do that in bulk on Linux, since I want to prevent people wasting time on this if they don't want/have to.

* Install `fontforge` on your preferred distro
* In your font folder **containing only the EightBit fonts**, create the folder "converted" and a script file (I named it ff.sh because yolo)
* Add the following contents to your script file:
```
#!fontforge
Open($1);
SetFontNames($fontname, $fontname);
Generate("converted/"+$fontname+".ttf");
```
* In the folder, execute ` for i in *.ttf; do fontforge -script ff.sh "$i"; done`

What this does (using fontforge) is to create a copy of every font and to put it in the "converted" folder while setting the family name of the font equal to the font name (which seperates all families). You can then use the converted font folder at your convenience.
