### ISSUE TITLE
"Russisch" TTF font doesn't match font sample PNG

### ISSUE THREAD

**Issue by spicyjack** [TheRobotFactory/EightBit-Atari-Fonts#2]
Hi,

The font `EightBit Atari-Russisch` font sample doesn't match the TTF font that's distributed in the Git repo.

Screenshot attached.  It looks like a Hebrew-ish font got copied into the place of `EightBit Atari-Russisch`.

Thanks!

<img width="592" alt="EightBit_Atari_Russisch_font_incorrect 2020-07-13" src="https://user-images.githubusercontent.com/562120/87334017-def5c580-c4f2-11ea-875e-2f757e44e57e.png">

**Comment by a8bit** [comment]
The font is correct. The Cyrillic characters are not mapped to the usual unicode locations. 
If you look at the "standard" font preview you can see it shows puctuation/numbers, then upper case, then box drawing, then lower case. 
![EightBit Atari-Regular-sample](https://user-images.githubusercontent.com/12753/87335863-934d1700-c506-11ea-9440-b00fa8a6f177.png)

The Russisch font shows the Cyrillic characters are mapped to the box drawing and lower case letters.

![EightBit Atari-Russisch-sample](https://user-images.githubusercontent.com/12753/87336059-eaeb8280-c506-11ea-9370-62bddc391497.png)

The hebrew, european, hebrew and najm characters are from official Atari fonts so I've mapped those where I could in the correct unicode space, all of these fonts include those characters. The cyrillic characters here are mapped to where they were mapped on the Atari.

**Comment by spicyjack** [comment]
Ahh, I see them now, I switched to "Repertiore" view in FontBook on macOS, and I can scroll through all of the glyphs in the font.  Sorry about the noise, thanks.
