### ISSUE TITLE
Font failed to preview in README

### ISSUE THREAD

**Issue by haunt98** [TheRobotFactory/EightBit-Atari-Fonts#3]
![Screenshot_2022-05-19-12-21-15-778_com.github.android.jpg](https://user-images.githubusercontent.com/5424272/169216556-84bfbf0c-be3a-4638-86f5-f946ad187441.jpg)

**Comment by a8bit** [comment]
Works ok here. 
<img width="949" alt="Screen Shot 2022-05-19 at 05 42 15" src="https://user-images.githubusercontent.com/12753/169275510-e5a07d9b-d236-4030-9b58-e3c1883c8141.png">
